agregar configuración de compilación dinámica para Docker y mejorar el flujo de trabajo de GitHub Actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -55,12 +55,27 @@ jobs:
             exit 1
           fi
 
+      - name: Determine Angular build configuration
+        id: build_config
+        run: |
+          if [ "${GITHUB_REF##*/}" == "main" ]; then
+            echo "config=production" >> $GITHUB_ENV
+          elif [ "${GITHUB_REF##*/}" == "develop" ]; then
+            echo "config=development" >> $GITHUB_ENV
+          elif [ "${GITHUB_REF##*/}" == "qa" ]; then
+            echo "config=qa" >> $GITHUB_ENV
+          else
+            echo "Error: branch name not recognized"
+            exit 1
+          fi
+
       - name: Build and push Docker image to Docker Hub
         uses: docker/build-push-action@v2
         with:
           context: .
           push: true
           file: ./Dockerfile
+          build-args: CONFIGURATION=${{ env.config }}
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/drivers-front:${{ env.tag }}
 
       - name: Set up Google Cloud authentication
